export const runJudgeABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_usdc', type: 'address', internalType: 'address' },
      { name: '_agent', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'agent',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'challengeParticipants',
    inputs: [
      { name: 'challengeId', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'challenges',
    inputs: [{ name: 'challengeId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'startTime', type: 'uint40', internalType: 'uint40' },
      { name: 'distance', type: 'uint32', internalType: 'uint32' },
      { name: 'entryFee', type: 'uint256', internalType: 'uint256' },
      { name: 'isActive', type: 'bool', internalType: 'bool' },
      { name: 'winner', type: 'address', internalType: 'address' },
      { name: 'totalPrize', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createChallenge',
    inputs: [
      { name: 'startTime', type: 'uint40', internalType: 'uint40' },
      { name: 'distance', type: 'uint32', internalType: 'uint32' },
      { name: 'entryFee', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'declareWinner',
    inputs: [
      { name: 'challengeId', type: 'uint256', internalType: 'uint256' },
      {
        name: 'stravaActivityId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'joinChallenge',
    inputs: [{ name: 'challengeId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'nextChallengeId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'participants',
    inputs: [
      { name: 'challengeId', type: 'uint256', internalType: 'uint256' },
      { name: 'participant', type: 'address', internalType: 'address' },
    ],
    outputs: [
      { name: 'hasJoined', type: 'bool', internalType: 'bool' },
      { name: 'hasSubmitted', type: 'bool', internalType: 'bool' },
      {
        name: 'stravaActivityId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setAgent',
    inputs: [{ name: '_agent', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'submitResult',
    inputs: [
      { name: 'challengeId', type: 'uint256', internalType: 'uint256' },
      {
        name: 'stravaActivityId',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'usdc',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'ChallengeCreated',
    inputs: [
      {
        name: 'challengeId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'startTime',
        type: 'uint40',
        indexed: false,
        internalType: 'uint40',
      },
      {
        name: 'distance',
        type: 'uint32',
        indexed: false,
        internalType: 'uint32',
      },
      {
        name: 'entryFee',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChallengeJoined',
    inputs: [
      {
        name: 'challengeId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'participant',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ResultSubmitted',
    inputs: [
      {
        name: 'challengeId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'participant',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'stravaActivityId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'WinnerDeclared',
    inputs: [
      {
        name: 'challengeId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'stravaActivityId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'winner',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'prize',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'AlreadyJoined', inputs: [] },
  { type: 'error', name: 'AlreadySubmitted', inputs: [] },
  { type: 'error', name: 'ChallengeNotActive', inputs: [] },
  { type: 'error', name: 'ChallengeNotStarted', inputs: [] },
  { type: 'error', name: 'ChallengeStarted', inputs: [] },
  { type: 'error', name: 'InvalidAddress', inputs: [] },
  { type: 'error', name: 'NotJoined', inputs: [] },
  { type: 'error', name: 'OnlyAgent', inputs: [] },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'PrizeTransferFailed', inputs: [] },
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'StartTimeInPast', inputs: [] },
  { type: 'error', name: 'USDCTransferFailed', inputs: [] },
  { type: 'error', name: 'WinnerNotSubmitted', inputs: [] },
] as const;
